// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    {
      type: "doc",
      label: "Overview",
      id: "index",
    },
    {
      type: "category",
      label: "Jupiter Spot",
      items: [
        {
          type: "category",
          label: "Jupiter Swap",
          items: [
            {
              type: "autogenerated",
              dirName: "2-jupiter-spot/2-jupiter-swap",
            },
            {
              type: "link",
              label: "Swap Features",
              href: "/features",
            },
          ],
        },
        {
          type: "category",
          label: "Limit Order",
          items: [
            {
              type: "autogenerated",
              dirName: "2-jupiter-spot/3-limit-order",
            },
          ],
        },
        {
          type: "category",
          label: "DCA",
          items: [
            {
              type: "autogenerated",
              dirName: "2-jupiter-spot/4-dca",
            },
          ],
        },
        {
          type: "category",
          label: "VA",
          items: [
            {
              type: "autogenerated",
              dirName: "2-jupiter-spot/5-va",
            },
          ],
        },
        // Add more categories under Jupiter Spot if needed
      ],
    },
    {
      type: "category",
      label: "Ape",
      items: [
        {
          type: "autogenerated",
          dirName: "6-ape",
        },
      ],
    },
    {
      type: "category",
      label: "JLP",
      items: [
        {
          type: "autogenerated",
          dirName: "7-jlp",
        },
      ],
    },
    {
      type: "category",
      label: "JupSOL",
      items: [
        {
          type: "autogenerated",
          dirName: "9-jupsol",
        },
      ],
    },
    {
      type: "category",
      label: "Perpetual Exchange",
      items: [
        {
          type: "autogenerated",
          dirName: "8-perpetual-exchange",
        },
      ],
    },
    {
      type: "category",
      label: "Bridge",
      items: [
        {
          type: "autogenerated",
          dirName: "10-bridge",
        },
      ],
    },
    {
      type: "category",
      label: "JupiterLock",
      items: [
        {
          type: "autogenerated",
          dirName: "11-jupiter-lock",
        },
      ],
    },
    {
      type: "category",
      label: "General",
      items: [
        {
          type: "autogenerated",
          dirName: "12-general",
        },
      ],
    },
    // Add more top-level categories as needed
  ],
};

module.exports = sidebars;
